name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Heroku Action
      uses: CDNievas/heroku-action@v1.0
      with:
        heroku_api_key: ee61d726-a36d-4dc8-a475-e4eaf6d25f94
        heroku_email: karel789@hotmail.com
        heroku_app_name: hopperapi
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.3.0
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: CD 
      run: cd Hopper
    - name: Docker build 
      run: docker build -t hopperapi .
    - name: Heroku Login
      run: heroku login
    - name: Heroku Push
      run: heroku container:push -a hopperapi web
    - name: Heroku Release 
      run: heroku container:release -a hopperapi web



